"@sentrei/stg-www-thisweekindaos-com":
  component: "../../node_modules/@sls-next/serverless-component"
  inputs:
    build:
      cmd: "cp"
      args: ["-r", "../../dist/apps/www-thisweekindaos-com/.", "."]
      cwd: ./
      env: {}
    bucketRegion: "us-east-1"
    bucketName: "stg-thisweekindaos-com"
    certificateArn: "arn:aws:acm:us-east-1:404521130193:certificate/1764b5c6-18dc-4f61-96cd-97f3bfe6472b"
    domain: ["stg", "www", "thisweekindaos.com"]
    name:
      defaultLambda: "stg-www-thisweekindaos-com-lambda"
      apiLambda: "stg-www-thisweekindaos-com-api-lambda"
      imageLambda: "stg-www-thisweekindaos-com-image-lambda"
    runtime: "nodejs14.x"
    roleArn: "arn:aws:iam::404521130193:role/serverless/serverless-stg"
    timeout: 30
    useServerlessTraceTarget: true
