"@sentrei/www-metashop-wtf":
  component: "../../node_modules/@sls-next/serverless-component"
  inputs:
    build:
      cmd: "cp"
      args: ["-r", "../../dist/apps/www-metashop-wtf/.", "."]
      cwd: ./
      env: {}
    bucketRegion: "us-east-1"
    bucketName: "www-metashop-wtf"
    certificateArn: "arn:aws:acm:us-east-1:404521130193:certificate/249913c2-1d8a-4835-b686-323a9c9847f4"
    cloudfront:
      distributionId: E3HS5S0BSK3P91
    domain: ["metashop.wtf"]
    name:
      defaultLambda: "www-metashop-wtf-lambda"
      apiLambda: "www-metashop-wtf-api-lambda"
      imageLambda: "www-metashop-wtf-image-lambda"
    runtime: "nodejs14.x"
    roleArn: "arn:aws:iam::404521130193:role/serverless/serverless-prd"
    timeout: 30
    useServerlessTraceTarget: true
