name: Yarn
inputs:
  token:
    required: true
runs:
  using: "composite"
  steps:
    - if: github.event_name == 'push'
      uses: actions/checkout@v2
      with:
        token: ${{ inputs.token }}
    - if: github.event_name == 'pull_request'
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        token: ${{ inputs.token }}
    - id: nvm
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NVMRC }}
    - id: yarn-cache-dir
      run: |
        echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v2
      with:
        path: |
          ${{ steps.yarn-cache-dir.outputs.dir }}
        key: |
          yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-
    - run: |
        yarn install --frozen-lockfile
    - run: |
        yarn run lint
    - if: failure()
      run: |
        yarn run fix
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        GIT_AUTHOR_NAME: "sentrei-bot"
        GIT_COMMITTER_NAME: "sentrei-bot"
        GIT_AUTHOR_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
        GIT_COMMITTER_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
