name: Check
on:
  push:
    branches:
      - main
  pull_request:
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_BRANCH: ${{ github.event.number || github.ref }}
  NX_RUN_GROUP: ${{ github.run_id }}
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: nrwl/nx-set-shas@v1
      - if: github.event_name == 'push'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_TOKEN }}
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.BOT_TOKEN }}
      - id: nvm
        run: |
          echo ::set-output name=NVMRC::$(cat .nvmrc)
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run cloud:ci
      - run: |
          yarn run lint
      - run: |
          yarn run affected:apps
      - run: |
          yarn run affected:build
      - run: |
          yarn run affected:e2e
      - run: |
          yarn run affected:lint
      - run: |
          yarn run affected:test
      - run: |
          yarn run cloud:stop
      - if: github.event_name != 'pull_request'
        uses: nrwl/nx-tag-successful-ci-run@v1
      - if: failure()
        run: |
          yarn run fix
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_AUTHOR_NAME: "sentrei-bot"
          GIT_COMMITTER_NAME: "sentrei-bot"
          GIT_AUTHOR_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
          GIT_COMMITTER_EMAIL: "70007101+sentrei-bot@users.noreply.github.com"
  agents:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run cloud:start
