name: Test
on:
  push:
    branches:
      - alpha
      - beta
      - main
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.BOT_TOKEN }}
      - id: nvm
        run: |
          echo ::set-output name=NVMRC::$(cat .nvmrc)
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
            */*/node_modules
          key: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ steps.nvm.outputs.NVMRC }}-${{ runner.os }}-
      - run: |
          yarn install --frozen-lockfile
      - run: |
          yarn run test
      - uses: codecov/codecov-action@v2
        with:
          directory: coverage
      - uses: mxschmitt/action-tmate@v3
